# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.IntegerField()),
                ('CompanyName', models.CharField(max_length=100)),
                ('Trade', models.CharField(max_length=100)),
                ('Zip', models.CharField(max_length=6)),
            ],
        ),
    ]
