# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCustomerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('CustomerId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerId', models.IntegerField()),
                ('CompanyName', models.CharField(max_length=100)),
                ('CustomerSpend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsPro', models.BooleanField()),
                ('Password', models.CharField(max_length=100)),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Zip', models.CharField(max_length=6)),
                ('IsAvailable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCategoryUrlMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=300)),
                ('Category', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProCustomers',
        ),
    ]
